### ISSUE TITLE
Module test fails on docker/debian

### ISSUE THREAD

**Issue by melezhik** [kuerbis/Term-Choose-p6#2]
Hi! Maybe it's docker related issue ( limited terminal support? ) , but zef test fails there - 
http://repo.westus.cloudapp.azure.com/rakudist/reports/Term%3A%3AChoose/debian/1579231396.txt

HTH

Aleksei

**Comment by melezhik** [comment]
Looks good now.

http://repo.westus.cloudapp.azure.com/rakudist/reports/Term%3A%3AChoose/debian/1580826516.txt

**Comment by kuerbis** [comment]
If `TERM` is not set, `vt100` is now used as `tput`s terminal type.
