### ISSUE TITLE
The latest version install fails

### ISSUE THREAD

**Issue by melezhik** [kuerbis/Term-Choose-p6#4]
Hi! Looks like missing dependency issue 

https://gist.github.com/melezhik/89ea7808cbb345a7efe7c115f2199a08

HTH

Aleksei

**Comment by kuerbis** [comment]
It should now work with the new fixed version.

**Comment by melezhik** [comment]
cool, once RakuDist gets back I could check it

**Comment by melezhik** [comment]
fixed in 1.6.7
