### ISSUE TITLE
CI build fails on alpine

### ISSUE THREAD

**Issue by melezhik** [kuerbis/Term-Choose-p6#6]
Hi!

Here is the report - http://sparrowhub.io:2222/report/345

23:39:09 05/01/2022 [bash: run tests] :: ===> Testing: Term::Choose:ver<1.7.7>
23:39:30 05/01/2022 [bash: run tests] :: Aborting due to test failure: Term::Choose:ver<1.7.7> (use --force-test to override)
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] t/01-basic.t ......... ok
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] t/02-basic.t ......... ok
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] t/03.meta.t .......... ok
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] t/05.pod-coverage.t .. ok
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] t/20-arguments.t ..... ok
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] t/tput.t ............. Dubious, test returned 9
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] Failed 9/9 subtests 
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] 
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] Test Summary Report
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] -------------------
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] t/tput.t  (Wstat: 2304 Tests: 9 Failed: 9)
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose]   Failed tests:  1 2 3 4 5 6 7 8 9
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] Non-zero exit status: 9
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] Files=6, Tests=268,  20 wallclock secs
23:39:30 05/01/2022 [bash: run tests] :: [Term::Choose] Result: FAILED
23:39:30 05/01/2022 [bash: run tests] :: ===> Testing [FAIL]: Term::Choose:ver<1.7.7>
23:39:30 05/01/2022 [bash: run tests] :: task exit status: 1
HTH

Aleksei

**Comment by kuerbis** [comment]
There is now a new version (1.7.8).
Could you retry it with the new version.

**Comment by melezhik** [comment]
good now - http://sparrowhub.io:2222/report/371

**Comment by melezhik** [comment]
for the future you may set up this repo in SparkyCI and track builds there for new commits

**Comment by kuerbis** [comment]
Thanks, I'll take a look.
